# Generated by Django 4.1.7 on 2023-03-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_autor_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='tirulo',
            new_name='titulo',
        ),
    ]
