# Generated by Django 4.2.2 on 2023-06-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0005_rename_autores_livro_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autor',
            new_name='autores',
        ),
    ]
